import { lazy } from 'react'

export const LazyMuiComponents = {
  Accordion: lazy(() => import('@mui/material/Accordion')),
  AccordionActions: lazy(() => import('@mui/material/AccordionActions')),
  AccordionDetails: lazy(() => import('@mui/material/AccordionDetails')),
  AccordionSummary: lazy(() => import('@mui/material/AccordionSummary')),
  Alert: lazy(() => import('@mui/material/Alert')),
  AlertTitle: lazy(() => import('@mui/material/AlertTitle')),
  AppBar: lazy(() => import('@mui/material/AppBar')),
  Autocomplete: lazy(() => import('@mui/material/Autocomplete')),
  Avatar: lazy(() => import('@mui/material/Avatar')),
  AvatarGroup: lazy(() => import('@mui/material/AvatarGroup')),
  Backdrop: lazy(() => import('@mui/material/Backdrop')),
  Badge: lazy(() => import('@mui/material/Badge')),
  BottomNavigation: lazy(() => import('@mui/material/BottomNavigation')),
  BottomNavigationAction: lazy(
    () => import('@mui/material/BottomNavigationAction'),
  ),
  Box: lazy(() => import('@mui/material/Box')),
  Breadcrumbs: lazy(() => import('@mui/material/Breadcrumbs')),
  Button: lazy(() => import('@mui/material/Button')),
  ButtonBase: lazy(() => import('@mui/material/ButtonBase')),
  ButtonGroup: lazy(() => import('@mui/material/ButtonGroup')),
  Card: lazy(() => import('@mui/material/Card')),
  CardActionArea: lazy(() => import('@mui/material/CardActionArea')),
  CardActions: lazy(() => import('@mui/material/CardActions')),
  CardContent: lazy(() => import('@mui/material/CardContent')),
  CardHeader: lazy(() => import('@mui/material/CardHeader')),
  CardMedia: lazy(() => import('@mui/material/CardMedia')),
  Checkbox: lazy(() => import('@mui/material/Checkbox')),
  Chip: lazy(() => import('@mui/material/Chip')),
  CircularProgress: lazy(() => import('@mui/material/CircularProgress')),
  ClickAwayListener: lazy(() => import('@mui/material/ClickAwayListener')),
  Collapse: lazy(() => import('@mui/material/Collapse')),
  DefaultPropsProvider: lazy(
    () => import('@mui/material/DefaultPropsProvider'),
  ),
  Dialog: lazy(() => import('@mui/material/Dialog')),
  DialogActions: lazy(() => import('@mui/material/DialogActions')),
  DialogContent: lazy(() => import('@mui/material/DialogContent')),
  DialogContentText: lazy(() => import('@mui/material/DialogContentText')),
  DialogTitle: lazy(() => import('@mui/material/DialogTitle')),
  Divider: lazy(() => import('@mui/material/Divider')),
  Drawer: lazy(() => import('@mui/material/Drawer')),
  Fab: lazy(() => import('@mui/material/Fab')),
  Fade: lazy(() => import('@mui/material/Fade')),
  FilledInput: lazy(() => import('@mui/material/FilledInput')),
  FormControl: lazy(() => import('@mui/material/FormControl')),
  FormControlLabel: lazy(() => import('@mui/material/FormControlLabel')),
  FormGroup: lazy(() => import('@mui/material/FormGroup')),
  FormHelperText: lazy(() => import('@mui/material/FormHelperText')),
  FormLabel: lazy(() => import('@mui/material/FormLabel')),
  Grid: lazy(() => import('@mui/material/Grid')),
  GridLegacy: lazy(() => import('@mui/material/GridLegacy')),
  Grow: lazy(() => import('@mui/material/Grow')),
  Icon: lazy(() => import('@mui/material/Icon')),
  IconButton: lazy(() => import('@mui/material/IconButton')),
  ImageList: lazy(() => import('@mui/material/ImageList')),
  ImageListItem: lazy(() => import('@mui/material/ImageListItem')),
  ImageListItemBar: lazy(() => import('@mui/material/ImageListItemBar')),
  InitColorSchemeScript: lazy(
    () => import('@mui/material/InitColorSchemeScript'),
  ),
  Input: lazy(() => import('@mui/material/Input')),
  InputAdornment: lazy(() => import('@mui/material/InputAdornment')),
  InputBase: lazy(() => import('@mui/material/InputBase')),
  InputLabel: lazy(() => import('@mui/material/InputLabel')),
  LinearProgress: lazy(() => import('@mui/material/LinearProgress')),
  Link: lazy(() => import('@mui/material/Link')),
  List: lazy(() => import('@mui/material/List')),
  ListItem: lazy(() => import('@mui/material/ListItem')),
  ListItemAvatar: lazy(() => import('@mui/material/ListItemAvatar')),
  ListItemButton: lazy(() => import('@mui/material/ListItemButton')),
  ListItemIcon: lazy(() => import('@mui/material/ListItemIcon')),
  ListItemSecondaryAction: lazy(
    () => import('@mui/material/ListItemSecondaryAction'),
  ),
  ListItemText: lazy(() => import('@mui/material/ListItemText')),
  ListSubheader: lazy(() => import('@mui/material/ListSubheader')),
  Menu: lazy(() => import('@mui/material/Menu')),
  MenuItem: lazy(() => import('@mui/material/MenuItem')),
  MenuList: lazy(() => import('@mui/material/MenuList')),
  MobileStepper: lazy(() => import('@mui/material/MobileStepper')),
  Modal: lazy(() => import('@mui/material/Modal')),
  NativeSelect: lazy(() => import('@mui/material/NativeSelect')),
  OutlinedInput: lazy(() => import('@mui/material/OutlinedInput')),
  OverridableComponent: lazy(
    () => import('@mui/material/OverridableComponent'),
  ),
  Pagination: lazy(() => import('@mui/material/Pagination')),
  PaginationItem: lazy(() => import('@mui/material/PaginationItem')),
  Paper: lazy(() => import('@mui/material/Paper')),
  PigmentContainer: lazy(() => import('@mui/material/PigmentContainer')),
  PigmentGrid: lazy(() => import('@mui/material/PigmentGrid')),
  PigmentStack: lazy(() => import('@mui/material/PigmentStack')),
  Popover: lazy(() => import('@mui/material/Popover')),
  Popper: lazy(() => import('@mui/material/Popper')),
  Portal: lazy(() => import('@mui/material/Portal')),
  Radio: lazy(() => import('@mui/material/Radio')),
  RadioGroup: lazy(() => import('@mui/material/RadioGroup')),
  Rating: lazy(() => import('@mui/material/Rating')),
  ScopedCssBaseline: lazy(() => import('@mui/material/ScopedCssBaseline')),
  Select: lazy(() => import('@mui/material/Select')),
  Skeleton: lazy(() => import('@mui/material/Skeleton')),
  Slide: lazy(() => import('@mui/material/Slide')),
  Slider: lazy(() => import('@mui/material/Slider')),
  Snackbar: lazy(() => import('@mui/material/Snackbar')),
  SnackbarContent: lazy(() => import('@mui/material/SnackbarContent')),
  SpeedDial: lazy(() => import('@mui/material/SpeedDial')),
  SpeedDialAction: lazy(() => import('@mui/material/SpeedDialAction')),
  SpeedDialIcon: lazy(() => import('@mui/material/SpeedDialIcon')),
  Stack: lazy(() => import('@mui/material/Stack')),
  Step: lazy(() => import('@mui/material/Step')),
  StepButton: lazy(() => import('@mui/material/StepButton')),
  StepConnector: lazy(() => import('@mui/material/StepConnector')),
  StepContent: lazy(() => import('@mui/material/StepContent')),
  StepIcon: lazy(() => import('@mui/material/StepIcon')),
  StepLabel: lazy(() => import('@mui/material/StepLabel')),
  Stepper: lazy(() => import('@mui/material/Stepper')),
  SvgIcon: lazy(() => import('@mui/material/SvgIcon')),
  SwipeableDrawer: lazy(() => import('@mui/material/SwipeableDrawer')),
  Switch: lazy(() => import('@mui/material/Switch')),
  Tab: lazy(() => import('@mui/material/Tab')),
  TabScrollButton: lazy(() => import('@mui/material/TabScrollButton')),
  Table: lazy(() => import('@mui/material/Table')),
  TableBody: lazy(() => import('@mui/material/TableBody')),
  TableCell: lazy(() => import('@mui/material/TableCell')),
  TableContainer: lazy(() => import('@mui/material/TableContainer')),
  TableFooter: lazy(() => import('@mui/material/TableFooter')),
  TableHead: lazy(() => import('@mui/material/TableHead')),
  TablePagination: lazy(() => import('@mui/material/TablePagination')),
  TablePaginationActions: lazy(
    () => import('@mui/material/TablePaginationActions'),
  ),
  TableRow: lazy(() => import('@mui/material/TableRow')),
  TableSortLabel: lazy(() => import('@mui/material/TableSortLabel')),
  Tabs: lazy(() => import('@mui/material/Tabs')),
  TextField: lazy(() => import('@mui/material/TextField')),
  TextareaAutosize: lazy(() => import('@mui/material/TextareaAutosize')),
  ToggleButton: lazy(() => import('@mui/material/ToggleButton')),
  ToggleButtonGroup: lazy(() => import('@mui/material/ToggleButtonGroup')),
  Toolbar: lazy(() => import('@mui/material/Toolbar')),
  Tooltip: lazy(() => import('@mui/material/Tooltip')),
  Typography: lazy(() => import('@mui/material/Typography')),
  Unstable_TrapFocus: lazy(() => import('@mui/material/Unstable_TrapFocus')),
  Zoom: lazy(() => import('@mui/material/Zoom')),
}
