services:
  material_ai:
    build: .
    environment:
     - SSO_ISSUER=${SSO_ISSUER}
     - SSO_CLIENT_ID=${SSO_CLIENT_ID}
     - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
     - SSO_REDIRECT_URI=${SSO_REDIRECT_URI}
     - SSO_SCOPE=${SSO_SCOPE}
     - SSO_SESSION_SECRET_KEY=${SSO_SESSION_SECRET_KEY}
     - CONFIG_PATH=${CONFIG_PATH}
     - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI}
     - GOOGLE_API_KEY=${GOOGLE_API_KEY}
     - ADK_SESSION_DB_URL=${ADK_SESSION_DB_URL}
    ports:
      - "8080:8080"
    volumes:
      # - ./src:/app/src
      - ./config.ini:/app/config.ini
