from google.adk.agents import LlmAgent, SequentialAgent
from material_ai.adk.agents import MaiAgent
from material_ai import get_config

config = get_config()
agent_env = config.get_agent("questionnaire_agent")
model = agent_env.get_env("model", "gemini-3-flash-preview")

# ---------------------------------------------------------
# Sub-Agent 1: Treatment Plan Specialist
# ---------------------------------------------------------
treatment_plan_agent = MaiAgent(
    name="treatment_plan_agent",
    model=model,
    additional_instructions="""
        You are an expert clinical strategist. Your task is to analyze the patient narrative provided.
        
        1. Extract current symptoms, medical history, active complaints, and relevant lifestyle factors from the narrative.
        2. Draft a comprehensive 'Next Treatment Plan' that includes:
           - Recommended clinical assessments or diagnostic tests.
           - Immediate medical or lifestyle interventions.
           - Medication adjustments if highlighted.
        3. Present the plan in a clear, structured clinical format using markdown headers.
        4. Save your final output to the session state so that the next agent can access it.
    """,
)

# ---------------------------------------------------------
# Sub-Agent 2: Flowchart Questionnaire Generator
# ---------------------------------------------------------
flowchart_generator_agent = MaiAgent(
    name="flowchart_generator_agent",
    model=model,
    additional_instructions="""
        You are a medical UX architect. Your task is to take the finalized Treatment Plan generated by the treatment_plan_agent and convert it into a binary (Yes/No) decision tree questionnaire.
        
        To ensure the generated flowchart looks elegant, highly professional, and consistent across all interactions (matching the style in image_a3e511.png), follow these design constraints:
        
        1. **Strict Tree Grid Layout Coordinates**:
           - Main vertical flow of Question nodes must run down the center at X = 250 (e.g., Node 1 at Y = 50, Node 2 at Y = 250, Node 3 at Y = 450).
           - Branching Clinical Action nodes must step horizontally to the right at X = 550, aligned vertically with their source question (e.g., Y = matching the source node).
           
        2. **Consistent Color & CSS Theme**:
           - **Question Nodes** (`type: "question"`): Use a professional slate-blue theme.
             - `style`: { "background": "#ffffff", "border": "2px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "boxShadow": "0 4px 6px -1px rgba(0,0,0,0.1)", "fontFamily": "system-ui, sans-serif" }
             - Map questions directly to validated REDCap schema fields from "test.json" (such as 'raynaud_s_yn', 'skin_tighter_yn', 'fingertips_ulcers_yn', or 'difficulty_breathing') using the `key` attribute.
           - **Action Nodes** (`type: "action"`): Use a warm clinical alert theme.
             - `style`: { "background": "#fffbeb", "border": "2px solid #f59e0b", "borderRadius": "8px", "padding": "16px", "boxShadow": "0 4px 6px -1px rgba(0,0,0,0.1)", "fontFamily": "system-ui, sans-serif" }
        
        3. **Elegant Edge Connections**:
           - Use orthogonal `"smoothstep"` edge styles.
           - **'Yes' Edges**: Must always be animated green dashed lines.
             - `style`: { "stroke": "#10b981", "strokeWidth": 2, "strokeDasharray": "5,5" }
             - `animated`: true
           - **'No' Edges**: Must always be solid red lines.
             - `style`: { "stroke": "#ef4444", "strokeWidth": 2 }
             - `animated`: false
    """,
)

# ---------------------------------------------------------
# Sequential Workflow: Chains both specialists
# ---------------------------------------------------------
narrative_workflow = SequentialAgent(
    name="narrative_workflow",
    sub_agents=[treatment_plan_agent, flowchart_generator_agent],
)

# ---------------------------------------------------------
# Root Orchestrator Agent
# ---------------------------------------------------------
root_agent = LlmAgent(
    name="questionnaire_agent",
    model=model,
    description="Questionnaire generation agent based on patient narratives",
    instruction="""
        You are a compassionate healthcare provider coordinator orchestrating a patient intake and assessment pipeline. 
        
        Your workflow is as follows:
        
        1. **Intake Prompt**: 
           When the user initiates the conversation, warmly welcome them and explicitly ask them to upload the raw patient narrative file. Use this exact phrase: 
           "Please upload the patient's clinical narrative or intake notes to begin generating the treatment plan and follow-up questionnaire."
        
        2. **Handoff Execution**: 
           Once the patient narrative is successfully uploaded, delegate the task to your sub-agent `narrative_workflow`.
           The workflow will execute sequentially:
    """,
    sub_agents=[narrative_workflow],
)
