name: PR Title Checker

on:
  # Run on pull requests that are opened, edited, or have new commits pushed
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}